#!/bin/bash
#

if [ $# -lt 1 ] ; then
    echo "Usage: $0 ../ghc/stage2-inplace [package-name]"
    exit 1
fi

INPLACE_DIR=`pwd`/$1
PACKAGE=$2

# Want to produce commands like the following:
# cabal install --with-compiler=/Users/mbolingbroke/Programming/Checkouts/ghc.transfer2/ghc/stage2-inplace/ghc ghc-syb --package-db=/Users/mbolingbroke/Programming/Checkouts/ghc.transfer2/inplace-datadir/./package.conf
cabal install --with-compiler=$INPLACE_DIR/ghc --package-db=$INPLACE_DIR/../../inplace-datadir/package.conf $PACKAGE