#!/bin/bash
#

if [ $# -lt 1 ] ; then
    echo "Usage: $0 <ghc-dir> <cabal options>"
    exit 1
fi

INPLACE_DIR=$(cd $1/inplace; pwd); shift

cabal $* --with-ghc=$INPLACE_DIR/bin/ghc-stage2 --with-ghc-pkg=$INPLACE_DIR/bin/ghc-pkg --package-db=$INPLACE_DIR/lib/package.conf.d