#!/bin/sh

HERE=`pwd`

TEMP_DIR="/tmp/$(basename $0).$$"
LEFT_DIR="$TEMP_DIR/left"
RIGHT_DIR="$TEMP_DIR/right"
rm -rdf $TEMP_DIR
mkdir $TEMP_DIR
mkdir $LEFT_DIR
mkdir $RIGHT_DIR

cd $HERE
eval "LEFT_FILES=$1*"
for LEFT_FILE in $LEFT_FILES; do
    LEFT_FILE_BASE=`echo $LEFT_FILE | sed s,$1,,`
    cp $LEFT_FILE $LEFT_DIR/$LEFT_FILE_BASE
done

cd $HERE
eval "RIGHT_FILES=$2*"
for RIGHT_FILE in $RIGHT_FILES; do
    RIGHT_FILE_BASE=`echo $RIGHT_FILE | sed s,$2,,`
    cp $RIGHT_FILE $RIGHT_DIR/$RIGHT_FILE_BASE
done

/Applications/DiffMerge.app/Contents/MacOS/DiffMerge $LEFT_DIR $RIGHT_DIR &
