#!/bin/bash

my-cabal-install QuickCheck 1.2.0.0 || exit 1
my-cabal-install HUnit 1.2.2.1 || exit 1
my-cabal-install testpack 1.0.2 || exit 1
my-cabal-install mtl 1.1.0.2 || exit 1
my-cabal-install parsec 2.1.0.1 || exit 1
my-cabal-install mtlparse 0.0.1 || exit 1
my-cabal-install regexpr 0.5.1 || exit 1
my-cabal-install split 0.1.1 || exit 1
my-cabal-install hledger 0.6.1 || exit 1
my-cabal-install csv 0.1.1 || exit 1
my-cabal-install MonadCatchIO-mtl 0.2.0.0 || exit 1
my-cabal-install ghc-mtl 1.0.1.0 || exit 1
my-cabal-install ghc-paths 0.1.0.5 || exit 1
my-cabal-install haskell-src 1.0.1.3 || exit 1
my-cabal-install hint 0.3.1.0 || exit 1
my-cabal-install network 2.2.1.5 || exit 1
# Probably better versions available:
my-cabal-install regex-base 0.93.1 || exit 1
my-cabal-install regex-posix 0.93.1 || exit 1
my-cabal-install tagsoup 0.6 || exit 1
