#!/bin/sh

sudo port deactivate py25-pyqt4
sudo rm /opt/local/Library/Frameworks/Python.framework/Versions/2.5/bin/pylupdate4
sudo rm /opt/local/Library/Frameworks/Python.framework/Versions/2.5/bin/pyrcc4 
sudo rm /opt/local/Library/Frameworks/Python.framework/Versions/2.5/bin/pyuic4 
sudo rm -rd /opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/PyQt4
sudo rm -rd /opt/local/share/doc/py25-pyqt4/
sudo rm -rd /opt/local/share/sip/PyQt4/
